---
# Update APT configuration
- name: add universe repository
  apt_repository: >
    repo="deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename|lower}} universe"
    state=present
  register: universe_result
  when: should_run

# Download keys and package lists
- name: apt-get update
  apt: update_cache=yes cache_valid_time=0
  when: should_run and universe_result.changed

- name: install gdebi
  apt: name=gdebi
  when: should_run

- name: Install gdebi packages {{gdebi_package_files}}
  command: gdebi --non-interactive {{item}}
  with_items: "{{gdebi_package_files}}"
  when: should_run
  # Ansible 2.1.0.0
  changed_when: False
