---
- name: install python-apt on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import apt" ||
       (command -v apt-get && apt-get install -y python-apt);
    fi

- name: install python-pycurl on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if command -v apt-get; then
       python -c "import pycurl" ||
       (command -v apt-get && apt-get install -y python-pycurl);
    fi

# Update APT configuration
- name: add universe repository
  apt_repository: >
    repo="deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename|lower}} universe"
    state=present
  register: universe_result
  sudo: yes

# Download keys and package lists
- name: apt-get update
  apt: update_cache=yes cache_valid_time=0
  sudo: yes
  when: universe_result.changed

- name: install gdebi
  apt: name=gdebi
  sudo: yes

- name: Check if dropbox is installed
  command: dpkg-query -W dropbox
  register: check_dropbox
  failed_when: false
  changed_when: false

- name: Download Ubuntu dropbox package
  get_url: url={{dropbox_url_ubuntu_deb}} dest={{dropbox_tmp_deb}}
  when: check_dropbox.rc == 1

- name: Install Ubuntu dropbox package
  sudo: true
  command: gdebi --non-interactive {{dropbox_tmp_deb}}
  when: check_dropbox.rc == 1
